local ADDON_NAME, ns = ...

local HandyNotes = LibStub("AceAddon-3.0"):GetAddon("HandyNotes", true)
if not HandyNotes then return end

local iconLink = "Interface\\Addons\\" .. ADDON_NAME .. "\\images\\"

ns.icons = { 
["Dungeon"] = "Interface\\MINIMAP\\Dungeon",
["Raid"] = "Interface\\MINIMAP\\Raid",
["PassageDungeonRaidM"] = iconLink .. "PassageDungeonM",
["PassageDungeonM"] = iconLink .. "PassageDungeonM",
["PassageRaidM"] = iconLink .. "passageRaidM",
["PassageDungeonL"] = iconLink .. "PassageDungeonL",
["PassageRaidL"] = iconLink .. "passageRaidL",
["PassageDungeonRaidMultiM"] = iconLink .. "PassageDungeonRaidMultiM",
["PassageDungeonMultiM"] = iconLink .. "PassageDungeonMultiM",
["PassageRaidMultiM"] = iconLink .. "passageRaidMultiM",
["TravelL"] = iconLink .. "travelL",
["TravelM"] = iconLink .. "travelm",
["VDungeon"] = iconLink .. "vanilladungeons",
["VRaid"] = iconLink .. "vanilladungeons",
["VKey1"] = iconLink .. "vkey1",
["MultipleM"] = iconLink .. "multipleM",
["MultipleD"] = iconLink .. "multipleD",
["MultipleR"] = iconLink .. "multipleR",
["MultipleMgray"] = iconLink .. "multipleMgray",
["Locked"] = iconLink .. "gray",
["Zeppelin"] = iconLink .. "zeppelin",
["HZeppelin"] = iconLink .. "zeppelinH",
["AZeppelin"] = iconLink .. "zeppelinA",
["Portal"] = iconLink .. "portal",
["HPortal"] = "interface/minimap/vehicle-hordemageportal",
["APortal"] = "Interface/Minimap/Vehicle-AllianceMagePortal",
["Ship"] = iconLink .. "ship",
["HShip"] = iconLink .. "shipH",
["AShip"] = iconLink .. "shipA",
["Exit"] = "interface/TARGETINGFRAME/UI-RaidTargetingIcon_7",
["PassageUpL"] = iconLink .. "passageupL",
["PassageDownL"] = iconLink .. "passagedownL",
["PassageRightL"] = iconLink .. "passagerightL",
["PassageLeftL"] = iconLink .. "passageleftL",
["PassageUpM"] = iconLink .. "passageupM",
["PassageDownM"] = iconLink .. "passagedownM",
["PassageRightM"] = iconLink .. "passagerightM",
["PassageLeftM"] = iconLink .. "passageleftM",
["TransportHelper"] = iconLink .. "tport",
["OgreWaygate"] = "Interface/Minimap/Vehicle-AllianceWarlockPortal",
}


TextIcon = IconClass
TextIconMNL4 = TextIcon(iconLink .. "MNL4") 
TextIconPassageDungeonRaidM = TextIcon(iconLink .. "PassageDungeonRaidM", 64, 64, 10, 50, 50, 1)
TextIconPassageDungeonM = TextIcon(iconLink .. "PassageDungeonM", 64, 64, 10, 50, 50, 1)
TextIconPassageRaidM = TextIcon(iconLink .. "PassageRaidM", 64, 64, 10, 50, 50, 1)
TextIconPassageDungeonRaidMultiM = TextIcon(iconLink .. "PassageDungeonRaidMultiM", 64, 64, 10, 50, 50, 1)
TextIconPassageDungeonMultiM = TextIcon(iconLink .. "PassageDungeonMultiM", 64, 64, 10, 50, 50, 1)
TextIconPassageRaidMultiM = TextIcon(iconLink .. "PassageRaidMultiM", 64, 64, 10, 50, 50, 1)
TextIconPortal = TextIcon(iconLink .. "portal", 64, 64, 10, 50, 50, 1) --(0, 0, 0, 0, 0, 0 = horizontal reflection?, ?, skalierung?, y achse,? )
TextIconHPortal = TextIcon("Interface/Minimap/Vehicle-HordeMagePortal", 64, 64, 10, 50, 50, 1)
TextIconAPortal = TextIcon("Interface/Minimap/Vehicle-AllianceMagePortal", 64, 64, 10, 50, 50, 1)
TextIconDungeon = TextIcon("Interface\\MINIMAP\\Dungeon", 64, 64, 10, 50, 50, 1)
TextIconRaid = TextIcon("Interface\\MINIMAP\\Raid", 64, 64, 10, 50, 50, 1)
TextIconVDungeon = TextIcon(iconLink .. "vanilladungeons", 64, 64, 10, 50, 50, 1)
TextIconVRaid = TextIcon(iconLink .. "vanilladungeons", 64, 64, 10, 50, 50, 1)
TextIconVKey1 = TextIcon(iconLink .. "vkey1")
TextIconMultipleM = TextIcon(iconLink .. "multipleM", 64, 64, 10, 50, 50, 1)
TextIconMultipleD = TextIcon(iconLink .. "multipleD", 64, 64, 10, 50, 50, 1)
TextIconMultipleR = TextIcon(iconLink .. "multipleR", 64, 64, 10, 50, 50, 1)
TextIconMultipleMgray = TextIcon(iconLink .. "multipleMgray", 64, 64, 10, 50, 50, 1)
TextIconMultipleDgray = TextIcon(iconLink .. "multipleDgray", 64, 64, 10, 50, 50, 1)
TextIconMultipleRgray = TextIcon(iconLink .. "multipleRgray", 64, 64, 10, 50, 50, 1)
TextIconLocked = TextIcon(iconLink .. "gray", 64, 64, 10, 50, 50, 1)
TextIconZeppelin = TextIcon(iconLink .. "zeppelin")
TextIconHZeppelin = TextIcon(iconLink .. "zeppelinH")
TextIconAZeppelin = TextIcon(iconLink .. "zeppelinA")
TextIconShip = TextIcon(iconLink .. "ship")
TextIconHShip = TextIcon(iconLink .. "shipH")
TextIconAShip = TextIcon(iconLink .. "shipA")
TextIconExit = TextIcon("interface/TARGETINGFRAME/UI-RaidTargetingIcon_7", 64, 64, 10, 50, 50, 1)
TextIconPassageup = TextIcon(iconLink .. "PassageUpL")
TextIconPassagedown = TextIcon(iconLink .. "PassageDownL")
TextIconPassageright = TextIcon(iconLink .. "PassageRightL")
TextIconPassageleft = TextIcon(iconLink .. "PassageLeftL")
TextIconTravelL = TextIcon(iconLink .. "travelL")
TextIconTransportHelper = TextIcon(iconLink .. "tport", 64, 64, 10, 50, 50, 1)
TextIconOgreWaygate = TextIcon("Interface/Minimap/Vehicle-AllianceWarlockPortal", 64, 64, 10, 50, 50, 1)
TextIconCheck = TextIcon("Interface/Buttons/UI-CheckBox-Up", 64, 64, 10, 50, 50, 1)
TextIconHorde = TextIcon("interface/pvprankbadges/pvprankhorde")
TextIconAlliance = TextIcon("interface/pvprankbadges/pvprankalliance")
TextIconTomTom = TextIcon(iconLink .."tomtompoint")
TextIconJournal = TextIcon("interface/icons/inv_misc_book_09")
TextIconKilledBosses = TextIcon("Interface/TargetingFrame/UI-RaidTargetingIcon_8")
TextIconKalimdor = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-Orc")
TextIconEK = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-Human")
TextIconBC = TextIcon("Interface/Icons/Achievement_Boss_Illidan")
TextIconNorthrend = TextIcon("interface/lfgframe/ui-lfr-portrait")
TextIconPandaria = TextIcon("Interface/CharacterFrame/TEMPORARYPORTRAIT-FEMALE-PANDAREN")
TextIconDraenor = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-MagharOrc")
TextIconLegion = TextIcon("Interface/Icons/artifactability_HavocDemonHunter_AnguishoftheDeceiver")
TextIconZandalar = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-ZandalariTroll")
TextIconKT = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-KulTiran")
TextIconSL = TextIcon("interface/icons/achievement_leader_sylvanas")
TextIconDF = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-Dracthyr")