local ADDON_NAME, ns = ...

local HandyNotes = LibStub("AceAddon-3.0"):GetAddon("HandyNotes", true)
if not HandyNotes then return end

local iconLink = "Interface\\Addons\\" .. ADDON_NAME .. "\\images\\"

ns.icons = { 
["Dungeon"] = "Interface\\MINIMAP\\Dungeon",
["Raid"] = "Interface\\MINIMAP\\Raid",
["PassageDungeonRaidM"] = iconLink .. "PassageDungeonM",
["PassageDungeonM"] = iconLink .. "PassageDungeonM",
["PassageRaidM"] = iconLink .. "passageRaidM",
["PassageDungeonL"] = iconLink .. "PassageDungeonL",
["PassageRaidL"] = iconLink .. "passageRaidL",
["PassageDungeonRaidMultiM"] = iconLink .. "PassageDungeonRaidMultiM",
["PassageDungeonMultiM"] = iconLink .. "PassageDungeonMultiM",
["PassageRaidMultiM"] = iconLink .. "passageRaidMultiM",
["TravelL"] = iconLink .. "travelL",
["TravelM"] = iconLink .. "travelm",
["TravelH"] = "interface/worldstateframe/hordeflag",
["TravelA"] = "interface/worldstateframe/allianceflag",
["VDungeon"] = iconLink .. "vanilladungeons",
["VRaid"] = iconLink .. "vanilladungeons",
["VKey1"] = iconLink .. "vkey1",
["MultipleM"] = iconLink .. "multipleM",
["MultipleD"] = iconLink .. "multipleD",
["MultipleR"] = iconLink .. "multipleR",
["MultipleMgray"] = iconLink .. "multipleMgray",
["Locked"] = iconLink .. "gray",
["Zeppelin"] = iconLink .. "zeppelin",
["HZeppelin"] = iconLink .. "zeppelinH",
["AZeppelin"] = iconLink .. "zeppelinA",
["Portal"] = iconLink .. "portal",
["HPortal"] = "interface/minimap/vehicle-hordemageportal",
["APortal"] = "Interface/Minimap/Vehicle-AllianceMagePortal",
["Ship"] = iconLink .. "ship",
["HShip"] = iconLink .. "shipH",
["AShip"] = iconLink .. "shipA",
["Exit"] = "interface/TARGETINGFRAME/UI-RaidTargetingIcon_7",
["PassageUpL"] = iconLink .. "passageupL",
["PassageDownL"] = iconLink .. "passagedownL",
["PassageRightL"] = iconLink .. "passagerightL",
["PassageLeftL"] = iconLink .. "passageleftL",
["PassageUpM"] = iconLink .. "passageupM",
["PassageDownM"] = iconLink .. "passagedownM",
["PassageRightM"] = iconLink .. "passagerightM",
["PassageLeftM"] = iconLink .. "passageleftM",
["TransportHelper"] = iconLink .. "tport",
["Tport2"] = iconLink .. "tport2",
["OgreWaygate"] = "Interface/Minimap/Vehicle-AllianceWarlockPortal",
["WayGateGolden"] = iconLink .. "WayGateGolden",
["WayGateGreen"] = iconLink .. "WayGateGreen",
["GPortal"] = iconLink .. "GPortal",
--portrait icons
["B11M"] = "interface/characterframe/temporaryportrait-male-bloodelf",
["MOrcF"] = "interface/characterframe/temporaryportrait-female-magharorc",
["OrcM"] = "interface/characterframe/temporaryportrait-male-orc",
["UndeadF"] = "interface/characterframe/temporaryportrait-female-scourge",
["GoblinF"] = "interface/characterframe/temporaryportrait-female-goblin",
["GilneanF"] = "interface/characterframe/temporaryportrait-female-gilnean",
["KulM"] = "interface/characterframe/temporaryportrait-male-kultiran",
["DwarfF"] = "interface/characterframe/temporaryportrait-female-dwarf",
}

TextIcon = IconClass
TextIconMNL4 = TextIcon(iconLink .. "MNL4") 
TextIconPassageDungeonRaidM = TextIcon(iconLink .. "PassageDungeonRaidM", 64, 64, 1, 50, 1, 50)
TextIconPassageDungeonM = TextIcon(iconLink .. "PassageDungeonM", 64, 64, 1, 50, 1, 50)
TextIconPassageRaidM = TextIcon(iconLink .. "PassageRaidM", 64, 64, 1, 50, 1, 50)
TextIconPassageDungeonRaidMultiM = TextIcon(iconLink .. "PassageDungeonRaidMultiM", 64, 64, 1, 50, 1, 50)
TextIconPassageDungeonMultiM = TextIcon(iconLink .. "PassageDungeonMultiM", 64, 64, 1, 50, 1, 50)
TextIconPassageRaidMultiM = TextIcon(iconLink .. "PassageRaidMultiM", 64, 64, 1, 50, 1, 50)
TextIconPortal = TextIcon(iconLink .. "portal", 64, 64, 1, 50, 1, 50) 
TextIconHPortal = TextIcon("Interface/Minimap/Vehicle-HordeMagePortal", 64, 64, 1, 50, 1, 50)
TextIconAPortal = TextIcon("Interface/Minimap/Vehicle-AllianceMagePortal", 64, 64, 1, 50, 1, 50)
TextIconDungeon = TextIcon("Interface\\MINIMAP\\Dungeon", 64, 64, 1, 50, 1, 50)
TextIconRaid = TextIcon("Interface\\MINIMAP\\Raid", 64, 64, 1, 50, 1, 50)
TextIconVDungeon = TextIcon(iconLink .. "vanilladungeons", 64, 64, 1, 50, 1, 50)
TextIconVRaid = TextIcon(iconLink .. "vanilladungeons", 64, 64, 1, 50, 1, 50)
TextIconVKey1 = TextIcon(iconLink .. "vkey1", 64, 64, 1, 50, 1, 50)
TextIconMultipleM = TextIcon(iconLink .. "multipleM", 64, 64, 1, 50, 1, 50)
TextIconMultipleD = TextIcon(iconLink .. "multipleD", 64, 64, 1, 50, 1, 50)
TextIconMultipleR = TextIcon(iconLink .. "multipleR", 64, 64, 1, 50, 1, 50)
TextIconMultipleMgray = TextIcon(iconLink .. "multipleMgray", 64, 64, 1, 50, 1, 50)
TextIconMultipleDgray = TextIcon(iconLink .. "multipleDgray", 64, 64, 1, 50, 1, 50)
TextIconMultipleRgray = TextIcon(iconLink .. "multipleRgray", 64, 64, 1, 50, 1, 50)
TextIconLocked = TextIcon(iconLink .. "gray", 64, 64, 1, 50, 1, 50)
TextIconZeppelin = TextIcon(iconLink .. "zeppelin", 64, 64, 1, 50, 1, 50)
TextIconHZeppelin = TextIcon(iconLink .. "zeppelinH", 64, 64, 1, 50, 1, 50)
TextIconAZeppelin = TextIcon(iconLink .. "zeppelinA", 64, 64, 1, 50, 1, 50)
TextIconShip = TextIcon(iconLink .. "ship", 64, 64, 1, 50, 1, 50)
TextIconHShip = TextIcon(iconLink .. "shipH", 64, 64, 1, 50, 1, 50)
TextIconAShip = TextIcon(iconLink .. "shipA", 70, 70, 1, 50, 1, 50)
TextIconExit = TextIcon("interface/TARGETINGFRAME/UI-RaidTargetingIcon_7", 64, 64, 1, 50, 1, 50)
TextIconPassageup = TextIcon(iconLink .. "PassageUpL", 50, 50, 1, 50, 1, 50)
TextIconPassagedown = TextIcon(iconLink .. "PassageDownL", 50, 50, 1, 50, 1, 50)
TextIconPassageright = TextIcon(iconLink .. "PassageRightL", 50, 50, 1, 50, 1, 50)
TextIconPassageleft = TextIcon(iconLink .. "PassageLeftL", 50, 50, 1, 50, 1, 50)
TextIconTravelA = TextIcon("interface/worldstateframe/allianceflag", 64, 64, 1, 50, 1, 50)
TextIconTravelH = TextIcon("interface/worldstateframe/hordeflag", 64, 64, 1, 50, 1, 50)
TextIconTravelL = TextIcon(iconLink .. "travelL", 64, 64, 1, 50, 1, 50)
TextIconTransportHelper = TextIcon(iconLink .. "tport", 64, 64, 1, 50, 1, 50)
TextIconTransport = TextIcon(iconLink .. "tport2", 64, 64, 1, 50, 1, 50)
TextIconWayGateGolden = TextIcon(iconLink .. "WayGateGolden", 50, 50, 1, 50, 1, 50)
TextIconWayGateGreen = TextIcon(iconLink .. "WayGateGreen", 50, 50, 1, 50, 1, 50)
TextIconOgreWaygate = TextIcon("Interface/Minimap/Vehicle-AllianceWarlockPortal", 64, 64, 1, 50, 1, 50)
TextIconCheck = TextIcon("Interface/Buttons/UI-CheckBox-Up", 64, 64, 1, 50, 1, 50)
TextIconHorde = TextIcon("interface/pvprankbadges/pvprankhorde")
TextIconAlliance = TextIcon("interface/pvprankbadges/pvprankalliance")
TextIconTomTom = TextIcon(iconLink .."tomtompoint")
TextIconJournal = TextIcon("interface/icons/inv_misc_book_09")
TextIconKilledBosses = TextIcon("Interface/TargetingFrame/UI-RaidTargetingIcon_8")
TextIconKalimdor = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-Orc")
TextIconEK = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-Human")
TextIconBC = TextIcon("Interface/Icons/Achievement_Boss_Illidan")
TextIconNorthrend = TextIcon("interface/lfgframe/ui-lfr-portrait")
TextIconPandaria = TextIcon("Interface/CharacterFrame/TEMPORARYPORTRAIT-FEMALE-PANDAREN")
TextIconDraenor = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-MagharOrc")
TextIconLegion = TextIcon("Interface/Icons/artifactability_HavocDemonHunter_AnguishoftheDeceiver")
TextIconZandalar = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Female-ZandalariTroll")
TextIconKT = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-KulTiran")
TextIconSL = TextIcon("interface/icons/achievement_leader_sylvanas")
TextIconDF = TextIcon("Interface/CharacterFrame/TemporaryPortrait-Male-Dracthyr")
TextIconDwarfF = TextIcon("interface/characterframe/temporaryportrait-female-dwarf")
TextIconGoblinF = TextIcon("interface/characterframe/temporaryportrait-female-goblin")
TextIconUndeadF = TextIcon("interface/characterframe/temporaryportrait-female-scourge")
TextIconGilneanF = TextIcon("interface/characterframe/temporaryportrait-female-gilnean")

-- 1 number --self.IconFileX = IconFileX or 0    -- the total X (horizontal) pixels in the image file - not just the icon we want
-- 2 number --self.IconFileY = IconFileY or 0    -- the total Y (vertical) pixels in the image file
-- 3 number --self.StartX = StartX or 0        -- The starting point in the file where the icon begins, counted from the left border, in pixels
-- 4 number --self.EndX = EndX or 0            -- The ending point in the file where the icon ends, counted from the left border, in pixels
-- 5 number --self.StartY = StartY or 0        -- The starting point in the file where the icon begins, counted from the top border, in pixels
-- 6 number --self.EndY = EndY or 0            -- The ending point in the file where the icon ends, counted from the top border, in pixels